name: my_compose_container_for_rozoviy_sad

services:
  nest-app:
    build:
      context: .
    entrypoint: ["/app/start.sh"]
    environment:
      - DATABASE_URL=${DATABASE_DOCKER_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_KEY=${JWT_KEY}
      - ESKIZ_EMAIL=${ESKIZ_EMAIL}
      - ESKIZ_PASSWORD=${ESKIZ_PASSWORD}
      - ADMIN_SURNAME=${ADMIN_SURNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_PHONE_NUMBER=${ADMIN_PHONE_NUMBER}
    env_file:
      - .env
    ports:
      - '8080:4000'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
volumes:
  my_volumes:
  redis_volumes:
